#!/usr/bin/env python3
"""Create N64Recomp TOML from a checked DKR Patch Pipeline policy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def string_list(entries: list[dict[str, object]]) -> str:
    return ", ".join(toml_string(str(entry["name"])) for entry in entries)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--policy", required=True, type=Path)
    parser.add_argument("--elf", required=True, type=Path)
    parser.add_argument("--rom", required=True, type=Path)
    parser.add_argument("--output-functions", required=True, type=Path)
    parser.add_argument("--entrypoint", required=True)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--use-mdebug", action="store_true")
    arguments = parser.parse_args()

    policy = json.loads(arguments.policy.read_text(encoding="utf-8"))
    if policy.get("schemaVersion") != 1:
        raise ValueError("unsupported Patch Pipeline policy schema")

    manual = ", ".join(
        "{ name = %s, section = %s, vram = %s, size = %s }"
        % (
            toml_string(str(entry["name"])),
            toml_string(str(entry["section"])),
            entry["vram"],
            entry["size"],
        )
        for entry in policy.get("manualFunctions", [])
    )
    sizes = ", ".join(
        "{ name = %s, size = %s }"
        % (toml_string(str(entry["name"])), entry["size"])
        for entry in policy.get("functionSizes", [])
    )
    patches = "\n\n".join(
        "[[patches.instruction]]\nfunc = %s\nvram = %s\nvalue = %s"
        % (toml_string(str(entry["function"])), entry["vram"], entry["value"])
        for entry in policy.get("instructionPatches", [])
    )
    hooks = "\n\n".join(
        "[[patches.hook]]\nfunc = %s\nbefore_vram = %s\ntext = %s"
        % (
            toml_string(str(entry["function"])),
            entry["beforeVram"],
            toml_string(str(entry["text"])),
        )
        for entry in policy.get("functionHooks", [])
    )

    content = f"""# Generated by scripts/generate_recomp_config.py.
# Do not hand-edit generated addresses; edit the versioned Patch Pipeline
# policy and regenerate this configuration.
[input]
entrypoint = {arguments.entrypoint}
use_mdebug = {str(arguments.use_mdebug).lower()}
elf_path = {toml_string(arguments.elf.resolve().as_posix())}
rom_file_path = {toml_string(arguments.rom.resolve().as_posix())}
output_func_path = {toml_string(arguments.output_functions.resolve().as_posix())}
manual_funcs = [{manual}]
function_sizes = [{sizes}]

[patches]
stubs = [{string_list(policy.get('stubs', []))}]
renamed = [{string_list(policy.get('renamed', []))}]
ignored = [{string_list(policy.get('ignored', []))}]

# BEGIN DKR_INSTRUCTION_PATCHES
{patches}
# END DKR_INSTRUCTION_PATCHES

# BEGIN DKR_FUNCTION_HOOKS
{hooks}
# END DKR_FUNCTION_HOOKS
"""
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
